# Generated by Django 5.2.5 on 2025-08-18 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_logininfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('contactnumber', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('profile', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.logininfo')),
            ],
        ),
    ]
