# Generated by Django 5.2.5 on 2025-08-18 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_userinfno'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfno',
            new_name='UserInfo',
        ),
    ]
